name: Faslet Composer Module

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nanasess/setup-php@master
        with:
          php-version: '7.4'
      - name: Run Composer Install
        run: composer install --no-interaction
      - name: Run Tests
        run: vendor/bin/phpunit --testdox tests
      - name: Slack Message
        if: startsWith(github.ref, 'refs/tags/')
        uses: dgoemans/slack-action@1.0.1
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        with:
          title: ${{ github.workflow }}
          title_link: "https://github.com/${{ github.repository }}"
          channel: "releases"
          text: |
            Release *PHP Module* :tada:
            Version: *<https://github.com/${{ github.repository }}/releases/tag/${{ github.event.release.tag_name }}|${{ github.event.release.tag_name }}>*
            ${{ github.event.release.name }}

            *Release notes:*
            ${{ github.event.release.body }}